// Generated by wrangler types (or manually maintained until run).

type CodingTaskMessage = import("./src/types").CodingTaskMessage;

interface Env {
  LINEAR_CLIENT_ID: string;
  LINEAR_CLIENT_SECRET: string;
  LINEAR_WEBHOOK_SECRET: string;
  WORKER_URL: string;
  OPENCODE_SERVER_URL: string;
  OPENCODE_SERVER_PASSWORD: string;
  LINEAR_TOKENS: KVNamespace;
  SESSION_STATE: KVNamespace;
  CODING_TASKS: Queue<CodingTaskMessage>;
}
